version: 2.1

jobs:
  # build_and_deploy_image:
  #   docker:
  #     - image: docker:latest
  #   steps:
  #     - checkout
  #     - setup_remote_docker:
  #         docker_layer_caching: false
  #     - run:
  #         name: Build Docker image
  #         command: |
  #           docker build -t acme-web-app -t tijani119/acme-web-app:3.0 .

  #     - run:
  #         name: Login to Docker Hub
  #         command: |
  #           echo $DOCKERHUB_PASSWORD | docker login -u tijani119 --password-stdin

  #     - run:
  #         name: Push Docker image to Docker Hub
  #         command: |
  #           docker push tijani119/acme-web-app:3.0

  deploy_to_eks_cluster:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Install AWS CLI
          command: |
            apt-get update -y
            apt-get install -y python3-pip
            pip3 install --upgrade pip
            pip3 install awscli

      - run:
          name: Verify AWS CLI Installation
          command: aws --version

      - run:
          name: Configure Kubeconfig
          command: |
            sudo apt-get update && sudo apt-get install -y kubectl
            aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

      - run:
          name: Deploy to AWS EKS
          command: |
            cd k8s-files
            kubectl apply -f .

workflows:
  project_workflow:
    jobs:
      - deploy_to_eks_cluster
